config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.jsc.fz-juelich.de/SLPP/pepc/pepc:
      branch: master
      repo: https://gitlab.jsc.fz-juelich.de/SLPP/pepc/pepc
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.jsc.fz-juelich.de/SLPP/pepc/pepc git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-rose-okapi.sh
        container: qc.acc_sickly-ecru-sheepdog
  QC.Doc:
    repos:
      gitlab.jsc.fz-juelich.de/SLPP/pepc/pepc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-yellow-catfish.sh
        container: qc.doc_wimpy-cerise-llama
      gitlab.jsc.fz-juelich.de/SLPP/pepc/pepc git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-heliotrope-squirrel.sh
        container: qc.doc_flaky-sangria-snake
      gitlab.jsc.fz-juelich.de/SLPP/pepc/pepc markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-teal-mongoose.sh
        container: qc.doc_bumpy-silver-corgi
  QC.Lic:
    repos:
      gitlab.jsc.fz-juelich.de/SLPP/pepc/pepc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-auburn-chihuahua.sh
        container: qc.lic_muzzy-champagne-lemming
  QC.Met:
    repos:
      gitlab.jsc.fz-juelich.de/SLPP/pepc/pepc cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-peach-cattle.sh
        container: qc.met_lumpy-ecru-burmese
  QC.Sec:
    repos:
      gitlab.jsc.fz-juelich.de/SLPP/pepc/pepc bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-vermilion-vulture.sh
        container: qc.sec_homely-ruby-bordeaux
  QC.Sty:
    repos:
      gitlab.jsc.fz-juelich.de/SLPP/pepc/pepc flake8:
        commands:
        - /usr/bin/env sh .sqa/script.randy-lemon-dingo.sh
        container: qc.sty_cheeky-cerulean-starfish
      gitlab.jsc.fz-juelich.de/SLPP/pepc/pepc hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-emerald-albatross.sh
        container: qc.sty_lousy-cinnamon-moose
  QC.Ver:
    repos:
      gitlab.jsc.fz-juelich.de/SLPP/pepc/pepc get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-chestnut-dog.sh
        container: qc.ver_scummy-olive-binturong
timeout: 5400
